name: 'C++ CI'

on:
  push:
    branches:
      - main
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Boost (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - name: Install Boost (Windows)
        if: runner.os == 'Windows'
        run: |
          vcpkg install boost-test --triplet x64-windows
          vcpkg integrate install
      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test_version
      - run: cmake --build . --target package
      - name: Create Release
        if: runner.os == 'Linux'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Ubuntu deb)
        if: runner.os == 'Linux'
        id: upload-release-asset-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./helloworld-1.0.${{ github.run_number }}-Linux.deb 
          asset_name: helloworld-1.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
